[tool.poetry]
name = "sycamore"
version = "0.1.0"
description = ""
authors = ["Vinayak Thapliyal <vinayak@aryn.ai>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
