[tool.poetry]
name = "crawler"
version = "0.1.0"
description = "Crawler to crawl your data source"
authors = ["aryn.ai <opensource@aryn.ai>"]
readme = "README.md"
repository = "https://github.com/aryn-ai/crawler.git"

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
boto3 = "^1.28.70"
scrapy = "^2.11.0"
types-python-dateutil = "^2.8.19.14"

[tool.poetry.group.test.dependencies]
flake8 = "4.0.1"
pytest = "7.4.0"
pytest-mock = "3.11.1"

[tool.poetry.group.dev.dependencies]
ruff = "^0.0.287"
black = "^23.7.0"
pre-commit = "^3.4.0"
mypy = "^1.5.1"

[tool.ruff]
line-length = 120

[tool.black]
line-length = 120

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
pythonpath = [ "." ]
