on:
  release:
    types: [published]

jobs:
  test-pypi-release:
    name: Upload to PyPI
    runs-on: ubuntu-latest
    environment:
      name: PyPI
      url: https://pypi.org/project/sycamore-ai/
    permissions:
      id-token: write
    steps:
      - name: Set Working Directory Env Var
        run: |
          if [[ ${{ github.ref }} =~ "sdk-v*" ]]; then
            echo "PROJECT_DIR=lib/aryn-sdk" >> "$GITHUB_ENV"
            echo "url=https://pypi.org/project/aryn-sdk/" >> "$GITHUB_ENV"
          else
            echo "PROJECT_DIR=lib/sycamore" >> "$GITHUB_ENV"
          fi;
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "poetry"
      - name: Install
        run: poetry install
        working-directory: ${{ env.PROJECT_DIR }}
      - name: build
        run: poetry build
        working-directory: ${{ env.PROJECT_DIR }}
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          packages-dir: ${{ env.PROJECT_DIR}}/dist
