name: Testing

on:
  push:
    branches:
      - bsowell/test-ocr-bug
  pull_request:
# Can't filter on paths easily and have required workflows.
# See https://github.com/orgs/community/discussions/13690 and
# https://engineering.mixpanel.com/enforcing-required-checks-on-conditional-ci-jobs-in-a-github-monorepo-8d4949694340

env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
  SYCAMORE_S3_TEMP_PATH: s3://aryn-sycamore-integ-temp/
  MODEL_SERVER_KEY: ${{ secrets.MODEL_SERVER_KEY }}
  PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
  ARYN_API_KEY: ${{ secrets.MODEL_SERVER_KEY }}
  SYCAMORE_HELICONE_API_KEY: ${{ secrets.HELICONE_API_KEY }}
  SYCAMORE_OPENAI_USER: 'sycamore-github-ci'
  SYCAMORE_HELICONE_TAG: ${{ github.ref }}

# Permissions for AWS access
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  sycamore-unit-tests:
    runs-on: ubuntu-latest #integ-test-runner2
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - name: DF-1
        run: df
      - name: du-runner-initial
        run: du -kx /home/runner | sort -rn | head -20
      - name: Move cache to /mnt
        run: sudo mkdir /mnt/cache && sudo chown $(whoami) /mnt/cache && mkdir -p /home/runner/.cache && sudo mount -o bind /mnt/cache /home/runner/.cache
      # Could free up other stuff as in:
      # https://github.com/easimon/maximize-build-space/blob/master/action.yml
      - name: Free up disk space
        run: sudo rm -rf /usr/local/lib/android
      - name: DF-2
        run: df
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"
      - name: DF-3
        run: df
      - name: Install sycamore
        run: poetry install --all-extras
        working-directory: lib/sycamore
      - name: DF-4
        run: df
      - name: Update Apt
        run: sudo apt-get update
      - name: Install apt dependencies
        run: sudo apt-get install -y poppler-utils tesseract-ocr libreoffice
      - name: DF-5
        run: df
      - name: Run tests
        run: |
          # Start resource monitoring in the background
          (
            while true; do
              top -b -n 1 | head -n 20 >> resource_usage.log
              free -m >> resource_usage.log
              df -h >> resource_usage.log
              echo "---" >> resource_usage.log
              sleep 60  # Collect data every 60 seconds
            done
          ) &

          # Store the background process ID
          echo "MONITOR_PID=$!" >> $GITHUB_ENV
          timeout 600 poetry run pytest -vv -s sycamore/tests/unit/transforms/test_detr_partitioner.py
          if [ $TEST_EXIT_CODE -eq 124 ]; then
            echo "Tests timed out after 10 minutes"
            exit 1
          elif [ $TEST_EXIT_CODE -ne 0 ]; then
            echo "Tests failed with exit code $TEST_EXIT_CODE"
            exit 1
          fi
        working-directory: lib/sycamore
        env:
          ACTIONS_STEP_DEBUG: true
      - name: Stop monitoring and upload logs
        if: always()
        run: |
          # Stop the resource monitoring
          if [ ! -z "$MONITOR_PID" ]; then
            kill $MONITOR_PID || true
          fi

          # Ensure the log file exists
          touch resource_usage.log

          # Add final system state
          echo "Final system state:" >> resource_usage.log
          top -b -n 1 | head -n 20 >> resource_usage.log
          free -m >> resource_usage.log
          df -h >> resource_usage.log
      - name: Upload resource usage logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: resource-usage-logs
          path: resource_usage.log
      - name: Run more tests
        run: poetry run python sycamore/tests/manual/test_fast_sycamore_import.py
        working-directory: lib/sycamore
      - name: DF-6
        run: df

